import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Upload, FileVideo, FileImage, ShieldAlert, CheckCircle2, 
  Loader2, Sparkles, Fingerprint, Search, Cpu, BarChart3, 
  Activity, AlertTriangle, Scan, Download, History, Trash2
} from 'lucide-react';
import { analyzeImageForensics } from '../services/forensicScanner';

const DetectionPage = () => {
  const [file, setFile] = useState(null);
  const [analyzing, setAnalyzing] = useState(false);
  const [scanStep, setScanStep] = useState(0);
  const [result, setResult] = useState(null);
  const [history, setHistory] = useState([]);

  useEffect(() => {
    const savedHistory = localStorage.getItem('forensic_history');
    if (savedHistory) {
      try {
        setHistory(JSON.parse(savedHistory));
      } catch (e) {
        console.error("Failed to parse history", e);
      }
    }
  }, []);

  const saveToHistory = (newResult, fileName) => {
    const historyItem = {
      id: Date.now(),
      timestamp: new Date().toLocaleString(),
      fileName,
      ...newResult
    };
    const updatedHistory = [historyItem, ...history.slice(0, 19)];
    setHistory(updatedHistory);
    localStorage.setItem('forensic_history', JSON.stringify(updatedHistory));
  };

  const deleteHistoryItem = (id) => {
    const updatedHistory = history.filter(item => item.id !== id);
    setHistory(updatedHistory);
    localStorage.setItem('forensic_history', JSON.stringify(updatedHistory));
  };

  const downloadReport = (data) => {
    const reportContent = `
VISION FORENSICS - AUTHENTICITY REPORT
---------------------------------------
Timestamp: ${data.timestamp || new Date().toLocaleString()}
File Name: ${data.fileName || 'N/A'}
Request ID: ${data.fingerprint}
Result: ${data.isAI ? 'AI SOURCE DETECTED' : 'AUTHENTIC CAPTURE'}
Probability: ${data.probability}%
Confidence: 98.4%

NEURAL BREAKDOWN:
- Pixel Noise Irregularity: ${data.breakdown.noiseLayers}%
- Metadata Authenticity: ${data.breakdown.metadata}%
- Contextual Consistency: ${data.breakdown.consistency}%

NOTES:
- High confidence score based on Sightengine neural cross-referencing.
- Analyzed via Vision Forensics Enterprise v3.0 Core.
---------------------------------------
Generated by Vision Forensics.
    `;
    
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Forensic_Report_${data.fileName || 'result'}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const scanPhases = [
    "Decrypting file metadata structure...",
    "Scanning pixel noise distribution (DFT)...",
    "Checking for GAN artifact signatures...",
    "Analyzing semantic inconsistencies...",
    "Neural Network cross-reference (100+ Models)...",
    "Finalizing authenticity report..."
  ];

  const handleFileChange = (e) => {
    const selected = e.target.files[0];
    if (selected) {
      setFile(selected);
      setResult(null);
      setScanStep(0);
    }
  };

  const startAnalysis = async () => {
    if (!file) return;
    setAnalyzing(true);
    setResult(null);
    setScanStep(0);
    
    try {
      if (!file.type.startsWith('image/') && !file.type.startsWith('video/')) {
        throw new Error('Please upload an image or video for neural scanning.');
      }
      
      const analysisResult = await analyzeImageForensics(file, (step) => {
        setScanStep(step);
      });
      
      const finalResult = {
        probability: analysisResult.probability,
        isAI: analysisResult.isAI,
        fingerprint: analysisResult.fingerprint,
        breakdown: {
          noiseLayers: analysisResult.breakdown.noiseLayers,
          metadata: analysisResult.breakdown.metadata,
          consistency: analysisResult.breakdown.consistency
        }
      };
      
      setResult(finalResult);
      saveToHistory(finalResult, file.name);
    } catch (error) {
      console.error("Forensic scan failed:", error);
      alert(error.message || "Forensic transmission failed.");
    } finally {
      setAnalyzing(false);
    }
  };

  return (
    <div className="container" style={{ paddingTop: 'clamp(100px, 12vh, 140px)', paddingBottom: '4rem' }}>
      <div className="mesh-gradient" />
      <div className="grid-overlay" />

      <div style={{ textAlign: 'center', marginBottom: '3rem' }}>
        <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }}>
          <div style={{ display: 'inline-flex', padding: '10px 20px', background: 'rgba(0, 242, 255, 0.1)', borderRadius: '100px', color: 'var(--accent-cyan)', fontSize: '0.8rem', fontWeight: 'bold', marginBottom: '1.5rem', border: '1px solid rgba(0, 242, 255, 0.2)' }}>
            <Scan size={14} style={{ marginRight: '8px' }} /> ADVANCED NEURAL FORENSICS
          </div>
          <h2 style={{ fontSize: 'clamp(2rem, 5vw, 3.5rem)', fontWeight: 900, marginBottom: '1rem' }}>
            Vision <span className="gradient-text">Forensics</span>
          </h2>
          <p style={{ color: 'var(--text-secondary)', maxWidth: '600px', margin: '0 auto', fontSize: 'clamp(0.9rem, 1.5vw, 1.1rem)' }}>
            Our deep-learning algorithm cross-references against 100+ known AI architectures to identify synthetic visual patterns with crystalline precision.
          </p>
        </motion.div>
      </div>

      <div className="glass cyber-border" style={{ padding: 'clamp(1.5rem, 5vw, 4rem)', textAlign: 'center', minHeight: '350px', display: 'flex', flexDirection: 'column', justifyContent: 'center', position: 'relative' }}>
        {analyzing && <div className="scanner-line" />}
        
        <input type="file" id="media-upload" hidden onChange={handleFileChange} accept="image/*,video/*" />
        
        {!file ? (
          <label htmlFor="media-upload" style={{ cursor: 'pointer', display: 'block' }}>
            <motion.div whileHover={{ scale: 1.05 }} style={{ display: 'inline-flex', padding: '1.5rem', background: 'rgba(255,255,255,0.03)', borderRadius: '50%', marginBottom: '1.5rem', border: '1px solid var(--glass-border)' }}>
              <Upload size={48} className="gradient-text" style={{ opacity: 0.8 }} />
            </motion.div>
            <h3 style={{ fontSize: '1.5rem', marginBottom: '1rem' }}>Ingest Media File</h3>
            <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem' }}>Drag and drop RAW files for deep forensic analysis</p>
          </label>
        ) : (
          <AnimatePresence mode="wait">
            {!analyzing && !result ? (
              <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '2rem', marginBottom: '2.5rem' }}>
                  <div className="glass" style={{ padding: '1.5rem', display: 'flex', alignItems: 'center', gap: '1rem', maxWidth: '100%', overflow: 'hidden' }}>
                    {file.type.startsWith('video') ? <FileVideo size={30} color="var(--accent-purple)" /> : <FileImage size={30} color="var(--accent-cyan)" />}
                    <div style={{ textAlign: 'left', overflow: 'hidden' }}>
                      <div style={{ fontWeight: 'bold', fontSize: '0.9rem', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{file.name}</div>
                      <div style={{ fontSize: '0.7rem', color: 'var(--text-secondary)' }}>SIZE: {(file.size / 1024 / 1024).toFixed(2)} MB</div>
                    </div>
                  </div>
                </div>
                <div style={{ display: 'flex', gap: '1rem', justifyContent: 'center' }} className="mobile-stack">
                  <button className="btn-primary" onClick={startAnalysis}>Run Full Neural Scan</button>
                  <button className="btn-secondary" style={{ padding: '14px 28px', color: 'var(--text-secondary)' }} onClick={() => setFile(null)}>Eject File</button>
                </div>
              </motion.div>
            ) : analyzing ? (
              <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} style={{ padding: '1rem' }}>
                <div style={{ position: 'relative', display: 'inline-block', marginBottom: '2rem' }}>
                  <motion.div animate={{ rotate: 360 }} transition={{ repeat: Infinity, duration: 4, ease: 'linear' }}>
                    <Fingerprint size={80} style={{ opacity: 0.1, color: 'var(--accent-cyan)' }} />
                  </motion.div>
                </div>
                <h3 className="gradient-text" style={{ fontSize: '1.2rem', marginBottom: '1rem' }}>{scanPhases[scanStep] || "Processing..."}</h3>
                <div style={{ maxWidth: '300px', height: '4px', background: 'rgba(255,255,255,0.05)', borderRadius: '10px', margin: '0 auto', overflow: 'hidden' }}>
                  <motion.div 
                    initial={{ width: 0 }} 
                    animate={{ width: `${(scanStep / scanPhases.length) * 100}%` }} 
                    style={{ height: '100%', background: 'var(--accent-cyan)', boxShadow: '0 0 10px var(--accent-cyan)' }} 
                  />
                </div>
              </motion.div>
            ) : null}
          </AnimatePresence>
        )}

        {result && !analyzing && (
          <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} style={{ marginTop: '1rem' }}>
            <div className="glass" style={{ 
              padding: 'clamp(1.5rem, 4vw, 3rem)', 
              borderColor: result.isAI ? 'var(--danger)' : 'var(--success)', 
              background: result.isAI ? 'rgba(255, 51, 102, 0.03)' : 'rgba(0, 255, 170, 0.03)',
              textAlign: 'left'
            }}>
              <div className="responsive-grid grid-2 mobile-stack" style={{ gap: '2rem' }}>
                <div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '15px', marginBottom: '1.5rem' }}>
                    {result.isAI ? <ShieldAlert size={32} color="var(--danger)" /> : <CheckCircle2 size={32} color="var(--success)" />}
                    <div>
                      <h3 style={{ fontSize: 'clamp(1.2rem, 3vw, 1.8rem)', color: result.isAI ? 'var(--danger)' : 'var(--success)' }}>
                        {result.isAI ? 'AI SOURCE DETECTED' : 'AUTHENTIC CAPTURE'}
                      </h3>
                      <p style={{ color: 'var(--text-secondary)', fontSize: '0.8rem' }}>ID: {result.fingerprint}</p>
                    </div>
                  </div>
                  
                  <div style={{ marginBottom: '2rem' }}>
                    <div style={{ fontSize: 'clamp(2.5rem, 6vw, 4rem)', fontWeight: 900 }}>
                      {result.probability}% <span style={{ fontSize: '1rem', color: 'var(--text-secondary)', fontWeight: 'normal' }}>AI Prob.</span>
                    </div>
                  </div>

                  <div style={{ display: 'flex', gap: '1rem' }} className="mobile-stack">
                    <button className="btn-primary" onClick={() => { setFile(null); setResult(null); }} style={{ justifyContent: 'center' }}>Reset</button>
                    <button 
                      className="btn-secondary" 
                      style={{ padding: '14px 24px', color: 'white', display: 'flex', alignItems: 'center', gap: '8px', justifyContent: 'center' }}
                      onClick={() => downloadReport({ ...result, fileName: file.name })}
                    >
                      <Download size={18} /> Report
                    </button>
                  </div>
                </div>

                <div style={{ background: 'rgba(0,0,0,0.2)', padding: '1.5rem', borderRadius: '16px', border: '1px solid var(--glass-border)' }}>
                  <h4 style={{ marginBottom: '1.25rem', display: 'flex', alignItems: 'center', gap: '10px', fontSize: '1rem' }}>
                    <BarChart3 size={18} color="var(--accent-cyan)" /> Neural Breakdown
                  </h4>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
                    {[
                      { label: 'Pixel Noise', val: result.breakdown.noiseLayers, color: 'var(--accent-cyan)' },
                      { label: 'Metadata', val: result.breakdown.metadata, color: 'var(--accent-purple)' },
                      { label: 'Consistency', val: result.breakdown.consistency, color: 'var(--accent-pink)' }
                    ].map((item, i) => (
                      <div key={i}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.75rem', marginBottom: '6px' }}>
                          <span style={{ color: 'var(--text-secondary)' }}>{item.label}</span>
                          <span style={{ fontWeight: 'bold' }}>{item.val}%</span>
                        </div>
                        <div style={{ height: '4px', background: 'rgba(255,255,255,0.05)', borderRadius: '10px', overflow: 'hidden' }}>
                          <motion.div initial={{ width: 0 }} animate={{ width: `${item.val}%` }} style={{ height: '100%', background: item.color }} />
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </motion.div>
        )}

        {/* History Section */}
        <div style={{ marginTop: '4rem', textAlign: 'left' }}>
          <h3 style={{ fontSize: '1.5rem', marginBottom: '1.5rem', display: 'flex', alignItems: 'center', gap: '12px' }}>
            <History size={20} color="var(--accent-cyan)" /> Forensic Audit History
          </h3>
          
          {history.length === 0 ? (
            <div className="glass" style={{ padding: '2rem', textAlign: 'center', color: 'var(--text-secondary)', borderRadius: '16px', fontSize: '0.9rem' }}>
              No previous scans detected.
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
              {history.map((item) => (
                <motion.div 
                  key={item.id} 
                  initial={{ opacity: 0, x: -10 }} 
                  animate={{ opacity: 1, x: 0 }}
                  className="glass" 
                  style={{ padding: '1rem 1.5rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderLeft: `3px solid ${item.isAI ? 'var(--danger)' : 'var(--success)'}`, borderRadius: '12px' }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: '1.5rem', overflow: 'hidden' }}>
                    <div style={{ overflow: 'hidden' }}>
                      <div style={{ fontWeight: 'bold', fontSize: '0.9rem', marginBottom: '2px', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{item.fileName}</div>
                      <div style={{ fontSize: '0.65rem', color: 'var(--text-secondary)' }}>{item.timestamp}</div>
                    </div>
                    <div className="mobile-hide" style={{ padding: '4px 10px', borderRadius: '100px', background: item.isAI ? 'rgba(255, 51, 102, 0.1)' : 'rgba(0, 255, 170, 0.1)', color: item.isAI ? 'var(--danger)' : 'var(--success)', fontSize: '0.65rem', fontWeight: 'bold', whiteSpace: 'nowrap' }}>
                      {item.isAI ? 'AI' : 'SAFE'} • {item.probability}%
                    </div>
                  </div>
                  
                  <div style={{ display: 'flex', gap: '0.5rem' }}>
                    <button onClick={() => downloadReport(item)} style={{ background: 'none', border: 'none', color: 'var(--text-secondary)', cursor: 'pointer', padding: '6px' }} className="glass-hover"><Download size={16} /></button>
                    <button onClick={() => deleteHistoryItem(item.id)} style={{ background: 'none', border: 'none', color: 'rgba(255,255,255,0.2)', cursor: 'pointer', padding: '6px' }} className="glass-hover"><Trash2 size={16} /></button>
                  </div>
                </motion.div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default DetectionPage;
